version: '3'
services:
    php:
        build:
            args:
                DOCKER_USER_UID: "${USER_UID:-1000}"
                DOCKER_USER_GID: "${USER_GID:-1000}"
            context: ./docker/php-fpm/.
        environment:
            #            Необходимо указать локальный IP для работы xdebug
            #            XDEBUG_CONFIG: remote_host=${IP_HOST}           # Подстановка хоста для Linux (в файле .env необходимо указать IP)
            #            XDEBUG_CONFIG: remote_host=host.docker.internal # Подстановка хоста для MAC и Windows
            XDEBUG_CONFIG:  remote_host=host.docker.internal
            PHP_IDE_CONFIG: "serverName=console"
        volumes:
            - ./:/var/www/app
            - ./docker/php-fpm/php.ini:/usr/local/etc/php/php.ini
            - ./docker/php-fpm/.ash_history:/home/docker-user/.ash_history
        depends_on:
            - postgres
        networks:
            - oop_net
    nginx:
        image: nginx:1.18.0-alpine
        ports:
            - "80:80"
        volumes:
            - ./:/var/www/app
            - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf
            - ./docker/nginx/logs:/var/log/nginx/
        depends_on:
            - php
        networks:
            - oop_net
    postgres:
        image:   postgres:12.2-alpine
        environment:
            POSTGRES_USER:     db_user
            POSTGRES_PASSWORD: db_pass
            POSTGRES_DB:       db_name
        volumes:
            - ./docker/postgres/data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - oop_net
networks:
    oop_net:
        driver: bridge
